<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Welcome to Borrow my Charger Web Application|Charger List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="assests/style.css" rel="stylesheet">
    <script src="assests/jquery-1.11.1.min.js"></script>
    <script src="assests/bootstrap.min.js"></script>
</head>

<body background="images/bg.jpeg">

    <fieldset>
        <div id="legend" style="background-color:#023020; height:40px">
            <legend class="" align="center" style="color:#FFFFFF">Login User Name : <?php echo  $_SESSION['fname']; ?></legend>

        </div>
        <br>
        <div class="control-group" align="center">
            <!-- Button -->
            <div class="controls">
                <a href="logout.php" class="btn btn-success" type="submit" name="signin">Logout</a>

                <?php if ($_SESSION['user_type'] == 'Home Owner') { ?>
                    <a href="add_charger.php" class="btn btn-success" type="submit" name="signin">Add Charger</a>
                    <a href="list.php" class="btn btn-success" type="submit" name="signin">All Chargers</a>
                <?php } else { ?>
                  <a href="list.php" class="btn btn-success" type="submit" name="signin">All chargers</a>
                  <?php
                } ?>
            </div>

        </div>

    </fieldset>

    <div class="container">
        <h2 style="color:#FFFFFF"> Charger List</h2>
        <table class="order-table table" style="color:#FFFFFF">
            <thead>
                <tr style="color:#FFFFFF">
                    <th>Sr. No</th>
                    <th><?php echo isset($_GET['charger_id']) ? "Renter Name" :" Owner Name" ?></th>
                    <th>Location</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Price/KWh</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $counter = 1;
                foreach ($view->bookingList as $charger) {

                ?>
                    <tr>
                        <td><?php echo $counter; ?></td>
                        <td><?php echo $charger->getOwnerName(); ?></td>
                        <td><?php echo $charger->getLocation(); ?> </td>
                        <td><?php echo $charger->getLat(); ?></td>
                        <td><?php echo $charger->getLog(); ?></td>
                        <td><?php echo $charger->getPrice(); ?></td>
                        <td><?php echo $charger->getStartDate(); ?></td>
                        <td><?php echo $charger->getEndDate(); ?></td>
                    </tr>
                <?php
                    $counter++;
                } ?>
            </tbody>
        </table>
    </div>
    <br><br><br><br><br><br><br><br><br><br>
    <?php require("Views/template/footer.phtml"); ?>

</body>

</html>